"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-11 16:16:47.302580
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role in ('student', 'parent', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('enrolments',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('class_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'class_id')
    )
    op.create_table('progress',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('chapter_id', sa.String(length=40), nullable=False),
    sa.Column('done', sa.JSON(), nullable=False),
    sa.Column('active', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chapter_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_user_id', ['user_id'], unique=False)

    op.create_table('voice_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=8), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('responses', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Integer(), nullable=False),
    sa.Column('input_audio', sa.Integer(), nullable=False),
    sa.Column('cached_text', sa.Integer(), nullable=False),
    sa.Column('cached_audio', sa.Integer(), nullable=False),
    sa.Column('output_text', sa.Integer(), nullable=False),
    sa.Column('output_audio', sa.Integer(), nullable=False),
    sa.Column('cost_estimate_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_usage')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_id')

    op.drop_table('sessions')
    op.drop_table('progress')
    op.drop_table('enrolments')
    op.drop_table('users')
    # ### end Alembic commands ###
