"""widen voice_usage.session_id

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-12 09:23:14.655615
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_usage', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_usage', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
