/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthAdminUsageRouteImport } from './routes/_auth/admin/usage'
import { Route as AuthCoursesIndexRouteImport } from './routes/_auth/courses/index'
import { Route as AuthCoursesCourseIdIndexRouteImport } from './routes/_auth/courses/$courseId/index'
import { Route as AuthCoursesCourseIdChaptersChapterIdIndexRouteImport } from './routes/_auth/courses/$courseId/chapters/$chapterId/index'
import { Route as AuthCoursesCourseIdChaptersChapterIdContentRouteImport } from './routes/_auth/courses/$courseId/chapters/$chapterId/content'
import { Route as AuthCoursesCourseIdChaptersChapterIdDiscussionRouteImport } from './routes/_auth/courses/$courseId/chapters/$chapterId/discussion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsageRoute = AuthAdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCoursesIndexRoute = AuthCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCoursesCourseIdIndexRoute =
  AuthCoursesCourseIdIndexRouteImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCoursesCourseIdChaptersChapterIdIndexRoute =
  AuthCoursesCourseIdChaptersChapterIdIndexRouteImport.update({
    id: '/courses/$courseId/chapters/$chapterId/',
    path: '/courses/$courseId/chapters/$chapterId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCoursesCourseIdChaptersChapterIdContentRoute =
  AuthCoursesCourseIdChaptersChapterIdContentRouteImport.update({
    id: '/courses/$courseId/chapters/$chapterId/content',
    path: '/courses/$courseId/chapters/$chapterId/content',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCoursesCourseIdChaptersChapterIdDiscussionRoute =
  AuthCoursesCourseIdChaptersChapterIdDiscussionRouteImport.update({
    id: '/courses/$courseId/chapters/$chapterId/discussion',
    path: '/courses/$courseId/chapters/$chapterId/discussion',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/settings': typeof AuthSettingsRoute
  '/admin/usage': typeof AuthAdminUsageRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/courses/': typeof AuthCoursesIndexRoute
  '/courses/$courseId/': typeof AuthCoursesCourseIdIndexRoute
  '/courses/$courseId/chapters/$chapterId/content': typeof AuthCoursesCourseIdChaptersChapterIdContentRoute
  '/courses/$courseId/chapters/$chapterId/discussion': typeof AuthCoursesCourseIdChaptersChapterIdDiscussionRoute
  '/courses/$courseId/chapters/$chapterId/': typeof AuthCoursesCourseIdChaptersChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/settings': typeof AuthSettingsRoute
  '/admin/usage': typeof AuthAdminUsageRoute
  '/admin': typeof AuthAdminIndexRoute
  '/courses': typeof AuthCoursesIndexRoute
  '/courses/$courseId': typeof AuthCoursesCourseIdIndexRoute
  '/courses/$courseId/chapters/$chapterId/content': typeof AuthCoursesCourseIdChaptersChapterIdContentRoute
  '/courses/$courseId/chapters/$chapterId/discussion': typeof AuthCoursesCourseIdChaptersChapterIdDiscussionRoute
  '/courses/$courseId/chapters/$chapterId': typeof AuthCoursesCourseIdChaptersChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/admin/usage': typeof AuthAdminUsageRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/courses/': typeof AuthCoursesIndexRoute
  '/_auth/courses/$courseId/': typeof AuthCoursesCourseIdIndexRoute
  '/_auth/courses/$courseId/chapters/$chapterId/content': typeof AuthCoursesCourseIdChaptersChapterIdContentRoute
  '/_auth/courses/$courseId/chapters/$chapterId/discussion': typeof AuthCoursesCourseIdChaptersChapterIdDiscussionRoute
  '/_auth/courses/$courseId/chapters/$chapterId/': typeof AuthCoursesCourseIdChaptersChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/settings'
    | '/admin/usage'
    | '/admin/'
    | '/courses/'
    | '/courses/$courseId/'
    | '/courses/$courseId/chapters/$chapterId/content'
    | '/courses/$courseId/chapters/$chapterId/discussion'
    | '/courses/$courseId/chapters/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/settings'
    | '/admin/usage'
    | '/admin'
    | '/courses'
    | '/courses/$courseId'
    | '/courses/$courseId/chapters/$chapterId/content'
    | '/courses/$courseId/chapters/$chapterId/discussion'
    | '/courses/$courseId/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/setup'
    | '/_auth/settings'
    | '/_auth/admin/usage'
    | '/_auth/admin/'
    | '/_auth/courses/'
    | '/_auth/courses/$courseId/'
    | '/_auth/courses/$courseId/chapters/$chapterId/content'
    | '/_auth/courses/$courseId/chapters/$chapterId/discussion'
    | '/_auth/courses/$courseId/chapters/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/usage': {
      id: '/_auth/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthAdminUsageRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/courses/': {
      id: '/_auth/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthCoursesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/courses/$courseId/': {
      id: '/_auth/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof AuthCoursesCourseIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/courses/$courseId/chapters/$chapterId/': {
      id: '/_auth/courses/$courseId/chapters/$chapterId/'
      path: '/courses/$courseId/chapters/$chapterId'
      fullPath: '/courses/$courseId/chapters/$chapterId/'
      preLoaderRoute: typeof AuthCoursesCourseIdChaptersChapterIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/courses/$courseId/chapters/$chapterId/content': {
      id: '/_auth/courses/$courseId/chapters/$chapterId/content'
      path: '/courses/$courseId/chapters/$chapterId/content'
      fullPath: '/courses/$courseId/chapters/$chapterId/content'
      preLoaderRoute: typeof AuthCoursesCourseIdChaptersChapterIdContentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/courses/$courseId/chapters/$chapterId/discussion': {
      id: '/_auth/courses/$courseId/chapters/$chapterId/discussion'
      path: '/courses/$courseId/chapters/$chapterId/discussion'
      fullPath: '/courses/$courseId/chapters/$chapterId/discussion'
      preLoaderRoute: typeof AuthCoursesCourseIdChaptersChapterIdDiscussionRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthAdminUsageRoute: typeof AuthAdminUsageRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthCoursesIndexRoute: typeof AuthCoursesIndexRoute
  AuthCoursesCourseIdIndexRoute: typeof AuthCoursesCourseIdIndexRoute
  AuthCoursesCourseIdChaptersChapterIdContentRoute: typeof AuthCoursesCourseIdChaptersChapterIdContentRoute
  AuthCoursesCourseIdChaptersChapterIdDiscussionRoute: typeof AuthCoursesCourseIdChaptersChapterIdDiscussionRoute
  AuthCoursesCourseIdChaptersChapterIdIndexRoute: typeof AuthCoursesCourseIdChaptersChapterIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSettingsRoute: AuthSettingsRoute,
  AuthAdminUsageRoute: AuthAdminUsageRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthCoursesIndexRoute: AuthCoursesIndexRoute,
  AuthCoursesCourseIdIndexRoute: AuthCoursesCourseIdIndexRoute,
  AuthCoursesCourseIdChaptersChapterIdContentRoute:
    AuthCoursesCourseIdChaptersChapterIdContentRoute,
  AuthCoursesCourseIdChaptersChapterIdDiscussionRoute:
    AuthCoursesCourseIdChaptersChapterIdDiscussionRoute,
  AuthCoursesCourseIdChaptersChapterIdIndexRoute:
    AuthCoursesCourseIdChaptersChapterIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
